.PHONY: require-workspace build build-sim clean typecheck lint lint-fix format format-check \
        check fix test test-ci coverage open help frameworks pods cordova-js \
        bridges setup

# Recipes run under bash, and every piped recipe starts with `set -o pipefail`.
#
# Without pipefail, `xcodebuild ... | tail -5` reports the exit status of `tail`, which
# is always 0 — so a FAILED BUILD EXITS 0. That is worse than a broken target, because
# it silently certifies broken code as good.
#
# `.SHELLFLAGS` is NOT used to do this: it requires GNU make >= 3.82 and macOS ships
# 3.81, where it is silently ignored — the fix would look applied and do nothing. The
# explicit `set -o pipefail` in each recipe works on every version.
SHELL := /bin/bash
.SHELLFLAGS := -o pipefail -c

# Configuration
#
# Builds MUST go through the workspace, not the .xcodeproj: Capacitor and Cordova are
# integrated via CocoaPods, and `-project` cannot resolve those modules — it fails with
# "Unable to resolve module dependency: 'Cordova'" before compiling any of our code.
PROJECT = iPadDx.xcodeproj
WORKSPACE = iPadDx.xcworkspace
TARGET = iPadDx
SDK = iphoneos
SCHEME = iPadDx
# Resolve an available iPad simulator at run time rather than pinning a model name.
#
# A hardcoded `name=iPad Pro 13-inch (M4)` breaks the moment that model is absent from
# the newest installed runtime: with no `OS=`, xcodebuild defaults to the LATEST runtime
# and reports "Unable to find a device matching the provided destination specifier",
# even though the device exists under an older runtime. Picking a UDID from whatever is
# actually installed works on any machine and on CI runners.
SIM_ID_IPAD := $(shell xcrun simctl list devices available 2>/dev/null | \
	grep -E '^ +iPad' | grep -oE '[0-9A-F]{8}-[0-9A-F-]{27}' | head -1)
SIM_ID_ANY := $(shell xcrun simctl list devices available 2>/dev/null | \
	grep -oE '[0-9A-F]{8}-[0-9A-F-]{27}' | head -1)
SIM_DEST = id=$(if $(SIM_ID_IPAD),$(SIM_ID_IPAD),$(SIM_ID_ANY))
SWIFT_FILES = $(shell find iPadDx -name "*.swift" -not -path "*/.*")

require-workspace:
	@if [ ! -f "$(WORKSPACE)/contents.xcworkspacedata" ]; then \
		echo ""; \
		echo "$(WORKSPACE) is missing or incomplete."; \
		echo ""; \
		echo "It is generated by CocoaPods and is not committed (neither is Pods/)."; \
		echo "Run 'make pods' — or 'make bridges' for the full bridge setup — then retry."; \
		echo ""; \
		exit 1; \
	fi

help: ## Show this help
	@# No pipefail here on purpose: grep exits 1 when it matches nothing, which would
	@# make `make help` fail spuriously. This target only prints text — it gates nothing.
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'

build: ## Build for device (no code signing)
	@$(MAKE) --no-print-directory require-workspace
	set -o pipefail; xcodebuild -workspace $(WORKSPACE) -scheme $(SCHEME) -sdk $(SDK) \
		-destination 'generic/platform=iOS' build \
		CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
		2>&1 | tail -5

build-sim: ## Build for iPad simulator
	@$(MAKE) --no-print-directory require-workspace
	set -o pipefail; xcodebuild -workspace $(WORKSPACE) -scheme $(SCHEME) -sdk iphonesimulator \
		-destination 'generic/platform=iOS Simulator' build \
		CODE_SIGNING_ALLOWED=NO \
		2>&1 | tail -5

clean: ## Clean build artifacts
	@$(MAKE) --no-print-directory require-workspace
	set -o pipefail; xcodebuild -workspace $(WORKSPACE) -scheme $(SCHEME) clean 2>&1 | tail -3
	rm -rf build/ DerivedData/

typecheck: ## Type-check via the workspace (bare swiftc cannot resolve the pods)
	@$(MAKE) --no-print-directory require-workspace
	@set -o pipefail; xcodebuild -workspace $(WORKSPACE) -scheme $(SCHEME) -sdk iphonesimulator \
		-destination 'generic/platform=iOS Simulator' build \
		CODE_SIGNING_ALLOWED=NO 2>&1 | grep -E "error:|BUILD" | tail -10

lint: ## Run SwiftLint
	@if command -v swiftlint >/dev/null 2>&1; then \
		swiftlint lint --config .swiftlint.yml iPadDx/; \
	else \
		echo "SwiftLint not installed. Run: brew install swiftlint" >&2; \
		exit 1; \
	fi

lint-fix: ## Run SwiftLint with auto-fix
	@if command -v swiftlint >/dev/null 2>&1; then \
		swiftlint lint --fix --config .swiftlint.yml iPadDx/; \
	else \
		echo "SwiftLint not installed. Run: brew install swiftlint"; \
	fi

format: ## Format Swift files with SwiftFormat
	@if command -v swiftformat >/dev/null 2>&1; then \
		swiftformat iPadDx/ --config .swiftformat; \
		echo "✓ Formatting complete"; \
	else \
		echo "SwiftFormat not installed. Run: brew install swiftformat"; \
	fi

format-check: ## Check formatting without modifying files
	@if command -v swiftformat >/dev/null 2>&1; then \
		swiftformat iPadDx/ --config .swiftformat --lint || \
			{ echo "✗ Formatting issues found" >&2; exit 1; }; \
		echo "✓ Formatting OK"; \
	else \
		echo "SwiftFormat not installed. Run: brew install swiftformat" >&2; \
		exit 1; \
	fi

test: ## Run unit tests on iPad simulator with coverage
	@$(MAKE) --no-print-directory require-workspace
	@if [ -z "$(SIM_ID_IPAD)$(SIM_ID_ANY)" ]; then \
		echo "No iOS Simulator available — install one via Xcode > Settings > Components." >&2; \
		exit 1; \
	fi
	@# The exit status is captured and re-raised at the end: coverage is still printed
	@# for a failing run, but `make test` MUST fail when a test fails.
	@# xcodebuild refuses to overwrite an existing result bundle, so a stale bundle
	@# makes every run after the first fail. The old `|| true` hid that entirely.
	@rm -rf build/TestResults.xcresult
	@set -o pipefail; status=0; \
	xcodebuild test \
		-workspace $(WORKSPACE) \
		-scheme $(SCHEME) \
		-destination '$(SIM_DEST)' \
		-enableCodeCoverage YES \
		-resultBundlePath build/TestResults.xcresult \
		2>&1 | { command -v xcbeautify >/dev/null 2>&1 && xcbeautify || cat; } || status=$$?; \
	echo ""; \
	echo "=== Coverage Report ==="; \
	xcrun xccov view --report --only-targets build/TestResults.xcresult 2>/dev/null || \
		echo "(no coverage data — the test run did not complete)"; \
	echo ""; \
	echo "Test results: build/TestResults.xcresult"; \
	if [ $$status -ne 0 ]; then echo "✗ Tests FAILED"; else echo "✓ Tests passed"; fi; \
	exit $$status

test-ci: ## Run tests without xcbeautify (for CI)
	@$(MAKE) --no-print-directory require-workspace
	@rm -rf build/TestResults.xcresult
	@set -o pipefail; status=0; \
	xcodebuild test \
		-workspace $(WORKSPACE) \
		-scheme $(SCHEME) \
		-destination '$(SIM_DEST)' \
		-enableCodeCoverage YES \
		-resultBundlePath build/TestResults.xcresult \
		2>&1 | tail -30 || status=$$?; \
	exit $$status
	xcrun xccov view --report --only-targets build/TestResults.xcresult

coverage: ## View coverage report from last test run
	@xcrun xccov view --report --only-targets build/TestResults.xcresult 2>/dev/null || \
		echo "No test results found. Run 'make test' first."

check: typecheck lint format-check ## Run all checks (typecheck + lint + format)

fix: lint-fix format ## Auto-fix lint issues and format code

open: ## Open the workspace in Xcode
	@$(MAKE) --no-print-directory require-workspace
	@# The workspace, never the .xcodeproj: the project alone cannot resolve the
	@# CocoaPods modules (Cordova, Capacitor).
	open $(WORKSPACE)

frameworks: ## Build embedded bridge frameworks from source
	@echo "Building Flutter bridge..."
	@set -o pipefail; cd Bridges/flutter_bridge && \
		flutter build ios-framework --no-debug --no-profile \
		--output=../../build/flutter_frameworks 2>&1 | tail -5
	@# Verify the artifacts before destroying the existing ones. `rm -rf` ran
	@# unconditionally, so a failed build left NO framework at all — the previous
	@# working copy was deleted before the replacement was known to exist.
	@for fw in Flutter App; do \
		if [ ! -d "build/flutter_frameworks/Release/$$fw.xcframework" ]; then \
			echo "flutter build produced no $$fw.xcframework — leaving Frameworks/ untouched" >&2; \
			exit 1; \
		fi; \
	done
	@mkdir -p Frameworks
	@rm -rf Frameworks/Flutter.xcframework Frameworks/App.xcframework
	@cp -R build/flutter_frameworks/Release/Flutter.xcframework Frameworks/
	@cp -R build/flutter_frameworks/Release/App.xcframework Frameworks/
	@echo "✓ Flutter frameworks built and copied to Frameworks/"

pods: ## Install CocoaPods dependencies (Capacitor + Cordova)
	@set -o pipefail; cd Bridges/capacitor_bridge && npm install 2>&1 | tail -3
	@set -o pipefail; pod install 2>&1 | tail -3
	@echo "✓ Pods installed — use iPadDx.xcworkspace from now on"

cordova-js: ## Copy real cordova.js into bundled resources
	@# Fails if `make pods` has not run: the source lives under node_modules.
	@if [ ! -f Bridges/capacitor_bridge/node_modules/@capacitor/core/cordova.js ]; then \
		echo "cordova.js not found — run 'make pods' first." >&2; exit 1; \
	fi
	@mkdir -p Bridges/cordova_bridge/www iPadDx/Resources/cordova_www
	@cp Bridges/capacitor_bridge/node_modules/@capacitor/core/cordova.js Bridges/cordova_bridge/www/cordova.js
	@cp Bridges/cordova_bridge/www/cordova.js iPadDx/Resources/cordova_www/cordova.js
	@cp Bridges/cordova_bridge/www/index.html iPadDx/Resources/cordova_www/index.html
	@echo "✓ cordova.js copied to cordova_www bundle"

bridges: frameworks pods cordova-js ## Build all bridge dependencies

setup: ## Install development dependencies
	brew install swiftlint swiftformat cocoapods
	brew install --cask flutter
	@echo "Then run: make bridges"
